version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
      dockerfile: ./prod.dockerfile
    command: gunicorn -w 4 short_url.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
