# syntax=docker/dockerfile:1
FROM python:3.8.16-slim-buster

# set environment variables for directories
ENV APP_HOME /app

# install dependencies
RUN apt-get update \
  && apt-get -y install libpq-dev gcc netcat \
  && pip install poetry

# set work directory
WORKDIR $APP_HOME

# set environment variables for python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install python dependencies
COPY poetry.lock pyproject.toml $APP_HOME
RUN poetry config virtualenvs.create false \
  && poetry install --no-root

# copy project
COPY . $APP_HOME

# run entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
