from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Url(models.Model):
    """URL model"""
    class Meta:
        verbose_name = _('link')
        verbose_name_plural = _('links')

    target_url = models.URLField(
        help_text=_('Target link for redirect')
    )
    uid = models.CharField(
        max_length=10,
        unique=True,
        help_text=_('Autogenerated identifier')
    )
    custom_uid = models.CharField(
        max_length=15,
        null=True,
        unique=True,
        help_text=_(
            'Additional user identifier (optional)'
        )
    )
    name = models.CharField(
        max_length=100,
        null=True,
        help_text=_('Link name (optional)')
    )
    click_count = models.IntegerField(
        default=0,
        help_text=_('Number of transitions')
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        help_text=_('User')
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text=_('Creation date')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text=_('Updated date')
    )

    def __str__(self):
        return self.uid
