# Generated by Django 4.1.4 on 2022-12-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='Целевая ссылка, на которую будет редирект')),
                ('uid', models.CharField(help_text='Автогенерируемый идентификатор', max_length=10, unique=True)),
                ('custom_uid', models.CharField(help_text='Дополнительный пользовательский идентификатор (опционально)', max_length=15, null=True, unique=True)),
                ('name', models.CharField(help_text='Имя ссылки (опционально)', max_length=100, null=True)),
                ('click_count', models.IntegerField(default=0, help_text='Количество переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления')),
                ('user', models.ForeignKey(help_text='Пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'ссылки',
            },
        ),
    ]
